### ISSUE TITLE
Using prefab.bash.envSet() fails

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/prefab9#115]
#### Installation information

- jumpscale version: 9.2.0
- operating system: Ubuntu 16.04

#### Detailed description

Using `prefab.bash.envSet()` fails with unlink: cannot unlink '/tmp': Permission denied 

#### Steps to reproduce

Blueprint:
```yaml
g8client__uk:
  url: 'uk-ln-vt-1.g8.gigukportal.tech'
  jwt: 'eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhenAiOiJlMnpsTi03U0M2N3RhdjN0UlJuZG9VQUd4a1U1IiwiZXhwIjoxNTEyNTA1NTM0LCJpc3MiOiJpdHN5b3VvbmxpbmUiLCJzY29wZSI6WyJ1c2VyOmFkbWluIl0sInVzZXJuYW1lIjoieXZlcyJ9.RpMuKyRDSSBelxS_lXPIdrtLYWFDAyUPuxzUS20QCdktPF6XWN5fKGpDeHkXASnRtQzbdGHlLOvvyR7vNZGaODdJBRzPrZ1MSIF5tyI8IvK-dhDThp4JtrU2Z1iIL8cu'
  account: 'Account_of_Artilium'

vdc__partnerportals2:
  g8client: 'uk'
  location: 'uk-ln-vt-1'

node.ovc__pphost:
    vdc: 'partnerportals2'
    bootdisk.size: 50
    memory: 4
    os.image: 'Ubuntu 16.04 x64'
    ports:
      - '2210:22'

partnerportal__mypp:
  os: 'pphost'
  vars:
    - 'var1="hello"'
    - 'var2="world"'
  url: 'https://docs.google.com/document/d/13sjWnnp_DZqChphna7SuQ3P7XaIe-P2Xdmwus_IkFpc'

actions:
  - action: install
```

Here's the `actions.py`:
```python
def install(job):
    service = job.service

    # Get prefab for cloudscaler, if not we get prefab for root
    #prefab = _get_prefab_for_cloudscaler(service)
    prefab = service.prefab

    try:
        b = prefab.bash
    except Exception as e:
        print("Error while accessing bash")

    data = j.data.serializer.json.loads(service.model.dataJSON)
    env_vars = data.get('vars', [])

    import ipdb;ipdb.set_trace()

    b.envSet("TEST", "Yves was here")
```

#### Relevant stacktraces

```python
         2017/12/04 20:11:33 trace: JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Cannot execute (ssh):
        set -e;bash -c "source /home/cloudscalers/.bash_profile; unlink /tmp"
        output:
        errors:
        unlink: cannot unlink '/tmp': Permission denied
         ((type:runtime.error)
```
