### ISSUE TITLE
Useless key/values in jumpscale9.toml

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/prefab9#140]
#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu 16.04

#### Detailed description

When activating ItsYou.online integration using `ays_host.prefab.js9.atyourservice.configure(production=True, organization="...")` following key/values are created in `jumpscale9.toml`:

```toml
[ays]
production = true

[ays.oauth]
jwt_key = "MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAES5X8XrfKdx9gYayFITc89wad4usrk0n27MjiGYvqalizeSWTHEpnd7oea9IQ8T5oJjMVH5cc0H5tFSKilFFeh//wngxIyny66+Vq5t5B0V0Ehy01+2ceEon2Y0XDkIKv"
client_id = ""
client_secret = ""
redirect_uri = "https://locahost:5000"
organization = "ays-server-clients-org"
```

As discussed and verified with @FastGeert and @LeeSmet, only `production`, `jwt_key` and `organization` are relevant/used. **Therefore please remove `client_id`, `client_secret` and `redirect_uri`** - currently they only confuse people.

The only thing AYS server does when receiving RESTful API calls is:
- Verify that the JWT has been issued by ItsYou.online (`jwt_key`)
- Verify that the JWT was created for the specified `organization` or for a user that is member of this organization

AYS does not need the other key/values since it does not create a JWT itself, and a `redirect_uri` is only relevant when using the authorization code grant flow, which AYS server doesn't use.

So only need following key/values:

```toml
[ays]
production = true

[ays.oauth]
jwt_key = "MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAES5X8XrfKdx9gYayFITc89wad4usrk0n27MjiGYvqalizeSWTHEpnd7oea9IQ8T5oJjMVH5cc0H5tFSKilFFeh//wngxIyny66+Vq5t5B0V0Ehy01+2ceEon2Y0XDkIKv"
organization = "ays-server-clients-org"
```

Also see https://github.com/Jumpscale/prefab9/issues/141 about the same key/values
