### ISSUE TITLE
Add extra argument to prefab.js9.atyourservice.configure to change the currently HARDCODED jwt_key

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/prefab9#141]
#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu 16.04

 
#### Detailed description

Currently `prefab.js9.atyourservice.configure(production=True, organization=<value>)` uses the paased value to set the value of the `organization` and hardcodes the value of the `jwt_key` to the public key of the production ItsYou.online.

This means that if you need to test against the stagging version of IYO that you manually need to update the `jumpscale9.toml`.

In order also allow to change this value through JumpScale we need an extra optional argument to change the value of `jwt_key`; if not specify use the default value as used now.

```toml
[ays]
production = true

[ays.oauth]
jwt_key = "MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAES5X8XrfKdx9gYayFITc89wad4usrk0n27MjiGYvqalizeSWTHEpnd7oea9IQ8T5oJjMVH5cc0H5tFSKilFFeh//wngxIyny66+Vq5t5B0V0Ehy01+2ceEon2Y0XDkIKv"
organization = "ays-server-clients-org"
```
